repos:
  - repo: https://github.com/gruntwork-io/pre-commit
    rev: v0.1.28
    hooks:
      - id: helmlint
  - repo: https://github.com/norwoodj/helm-docs
    rev: v1.14.2
    hooks:
      - id: helm-docs
