# apiVersion: cert-manager.io/v1
# kind: Certificate
# metadata:
#   name: uptime-kuma-cert
#   namespace: gallowhead
# spec:
#   secretName: uptime-kuma-cert
#   issuerRef:
#     name: letsencrypt-prod
#     kind: ClusterIssuer
#   dnsNames:
#     - uptime.baphomet.cloud
#     - www.uptime.baphomet.cloud